module Level.Decode exposing (decoder)


import Json.Decode exposing (Decoder, Error, Value)
import Json.Decode.Pipeline exposing (required)
import Level exposing (Level, Level_PreEncoded)
import Set exposing (Set(..))


decoder : Decoder Level
decoder =
    decoderForPreEncoded
        |> Json.Decode.map Level.fromPreEncoded



-- THE CODE BELOW IS GENERATED BY INTELLIJ ELM PLUGIN


decoderForPreEncoded : Decoder Level_PreEncoded
decoderForPreEncoded =
    Json.Decode.succeed Level_PreEncoded
