module Level.Encode exposing (encode)

import Json.Encode exposing (Value)
import Level exposing (Level, Level_PreEncoded)


encode : Level -> Value
encode =
    Level.toPreEncoded >> encodePrepared



-- THE CODE BELOW IS GENERATED BY INTELLIJ ELM PLUGIN


encodePrepared : Level_PreEncoded -> Value
encodePrepared levelToEncode =
    Json.Encode.object <|
        []
